replace ~/.config/bspwm/bspwm &
replace ~/.config/alacritty/alacritty.yml &
replace ~/.config/zathra/zathurarc &
numlockx &
dunst &
clipmenud &
picom --experimental-backends &
feh --bg-scale ~/Pictures/wall.* --no-fehbg &
setxkbmap -option caps:backspace &
xset r 66 &
pgrep -x sxhkd > /dev/null || sxhkd &
dwmblocks &
exec bspwm
