#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d   

bspc config top_padding 50
bspc config bottom_padding 20
bspc config left_padding 20
bspc config right_padding 20
bspc config border_width 2
bspc config window_gap 15

bspc config focus_follows_pointer true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color	"#83a598"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#458588"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#fb4934"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
bspc config -d ^1 window_gap 50
