#! /bin/sh

xrdb ~/.config/X11/.Xresources 
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config initial_polarity first_child
bspc config automatic_scheme spiral

bsp-layout set tall 2 --master-size 0.6

bspc config top_padding 40
bspc config bottom_padding 20
bspc config left_padding 20
bspc config right_padding 20
bspc config window_gap 15
bspc config border_width 3

bspc config focus_follows_pointer true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color '#4C566A'
bspc config active_border_color '#4C566A'
bspc config focused_border_color '#D8DEE9'
bspc config presel_feedback_color '#2E3440'
bspc config urgent_border_color '#BF616A'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
bspc rule -a Zathura state=tiled
bspc rule -a VirtualBox* state=tiled
bspc config -d ^2 window_gap 1
bspc config -d ^1 window_gap 0
bspc config -d ^1 left_padding -20
bspc config -d ^1 right_padding -20
bspc config -d ^1 bottom_padding -20
bspc config -d ^1 border_width 0
