xreplaceapps &
xautolock -time 10 -locker autolock -corners -000 &
numlockx &
dunst &
clipmenud &
feh --bg-scale ${DOTS}/wm/wallpaper.* --no-fehbg &
setxkbmap us -option caps:backspace &
xset r 66 &
pgrep -x sxhkd > /dev/null || sxhkd &
exec bspwm
