export _Z_DATA="$XDG_CACHE_HOME/z"
export WINSDD='/mnt/c/Users/agust'
export WINHDD='/mnt/d'
export DISPLAY=:0
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export ZSH="$HOME/.config/oh-my-zsh"
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_COLORS="7634"
# export TERMINAL="alacritty"
export NNN_BMS="d:$WINHDD;c:$WINSDD"
export NNN_OPTS="e"
export NNN_PLUG='s:suedit;'
export EDITOR="vim"
export READER="zathura"
export SCRIPT_DIR=~/.config/scripts
export AUTO_NOTIFY_TITLE="%command"
export AUTO_NOTIFY_BODY="Command completed in %elapsed seconds"
export AUTO_NOTIFY_IGNORE=("docker" "man" "sleep" "n" "ytop" "cmus")
