export SCRIPT_DIR=~/.config/scripts
export EDITOR=vim
export TERMINAL=alacritty
# export PAGER=zathura
export NNN_OPTS="He"
export NNN_COLORS='7777'
export NNN_BMS='f:~/Documents/Facultad;c:~/.config;l:~/.local/bin'
export NNN_PLUG='i:imgthumb;p:preview-tui;b:_feh --bg-fill $nnn;'
export NNN_FIFO='/tmp/nnn.fifo'
