export WINSDD='/mnt/c/Users/agust'
export WINHDD='/mnt/d'
export DISPLAY=:0
export SDKFOLDER="$HOME/sdk"
export ANDROID_HOME="$SDKFOLDER/android"
export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export ZSH="$XDG_CONFIG_HOME/oh-my-zsh"
# export ZDOTDIR="$XDG_DATA_HOME/zsh"
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export _Z_DATA="$XDG_CACHE_HOME/z"
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_COLORS="7634"
export NNN_BMS="d:$WINHDD;c:$WINSDD"
export NNN_OPTS="e"
export NNN_PLUG='s:suedit;'
export EDITOR="vim"
export READER="zathura"
export SCRIPT_DIR=~/.config/scripts
export AUTO_NOTIFY_TITLE="%command"
export AUTO_NOTIFY_BODY="Command completed in %elapsed seconds"
export AUTO_NOTIFY_IGNORE=("docker" "man" "sleep" "n" "ytop" "cmus")
