#! /usr/bin/zsh

passLength=10

userChoises="
agust_22_10@hotmail.com
agusdolard@gmail.com
agusdolard
agusd8
agusd
vvusie_"


url="$(echo '' | dmenu -p 'Url:')"
[[ -z $url ]] && exit 1
username="$(echo $userChoises | dmenu -p 'User:')"
[[ -z $username ]] && exit 1
siteName="$(echo '' | dmenu -p 'Name:')"
[[ -z $siteName ]] && exit 1

generated="$(lpass generate --url=$url --username=$username $siteName $passLength)"

echo $generated | xsel -b && notify-send "$siteName password generated" "Your new password has been copied to your clipboard"
