#!/bin/bash

title='Pomodoro'
resumecomment='Back to work bb'
breakcomment='Chill a bit'

# seconds
time=1500
breaktime=300

notify-send "${title}" "Here we go!"
sleep $time

while :
do
	sleep $breaktime
	notify-send "${title}"  "${resumecomment}"

	sleep $time
	notify-send "${title}"  "${breakcomment}"
done
