#!/bin/bash

DMENU=${DMENU:-dmenu}
PROMPT='QR Generator'
IMAGE_PATH='/tmp/qrcode.png'

CLIP="$(xsel -b -o)"

DATA="$(${DMENU} -it "$CLIP" -p "$PROMPT")"

qrencode -o $IMAGE_PATH $DATA
feh $IMAGE_PATH
