#!/bin/bash

DMENU=${DMENU:-dmenu}

prompt="Shutdown?"
cmd_list="Yes No Reboot"

ans="$(echo $cmd_list | sed 's/ /\n/g' | ${DMENU} -p "$prompt")"
[[ -z $ans ]] && exit 1

if [[ $ans = Yes ]]; then
	shutdown now
fi

if [[ $ans = Reboot ]]; then
	reboot
fi
